export const alphaBooths = [
  {
    boothNumber: "A01",
    isReserved: false,
    reservedBy: "Bunty Soap",
    powered: true,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A02",
    isReserved: false,
    reservedBy: "Cover 6 Outdoor Apparel",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A03",
    isReserved: false,
    reservedBy: "Cyberdyne Sytems",
    powered: true,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "A21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const bravoBooths = [
  {
    boothNumber: "B01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "B21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const charlieBooths = [
  {
    boothNumber: "C01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "C21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const deltaBooths = [
  {
    boothNumber: "D01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const echoBooths = [
  {
    boothNumber: "E01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const foxBooths = [
  {
    boothNumber: "E01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const golfBooths = [
  {
    boothNumber: "E01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const hotelBooths = [
  {
    boothNumber: "E01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 400,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 425,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 450,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 475,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 500,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 525,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 550,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const indiaBooths = [
  {
    boothNumber: "E01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "E04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 225,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 250,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 275,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 300,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 325,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "D14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 350,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const julietBooths = [
  {
    boothNumber: "J01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 100,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 125,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J10",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 150,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J11",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 175,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J12",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 200,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J13",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 100,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J14",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 125,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J15",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 150,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J16",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 175,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J17",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 200,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J18",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 100,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J19",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 125,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J20",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 150,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J21",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 175,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J22",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 200,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J23",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 250,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J24",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J25",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J26",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J27",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J28",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J29",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "J30",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 400,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const kiloBooths = [
  {
    boothNumber: "K01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "K02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];

export const limaBooths = [
  {
    boothNumber: "L01",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 0,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L02",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 25,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L03",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 50,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L04",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 75,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L05",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 100,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L06",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 125,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L07",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 0,
    y: 150,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L08",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 50,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  },
  {
    boothNumber: "L09",
    isReserved: false,
    reservedBy: "",
    powered: false,
    x: 75,
    y: 200,
    width: 20,
    height: 20,
    fill: "#799C8A"
  }
];
